deps:
	uv sync --locked

run:
	streamlit run src/main.py --server.address 0.0.0.0 --server.port 3000

dev:
	streamlit run src/main.py --server.address 0.0.0.0 --server.port 3000 --reload

shell:
	uv run sh
